seedco/Formalist

Formalist/FormValue.swift
Has to be public for framework consumers to use it in implementing custom form elements.
=> Make FormValue.value setter public

Formalist.xcodeproj/project.pbxproj, Formalist/Convenience.swift, Formalist/FloatLabelTextField.swift, FormalistTests/FloatLabelTests.swift
For single line float labels, create a `UITextField` subclass that automatically hides the placeholder when editing begins. Otherwise, both the field name label and the placeholder display the same thing and the information is redundant.
=> Auto hide placeholder when single line float label begins editing

Formalist/GroupElement.swift, Formalist/ValidationErrorView.swift, FormalistTests/ValidationErrorViewTests.swift
This is set up in the `validationErrorViewFactory` instead, so that a custom
factory can provide its own constraints.
=> Remove constant height constraint from ValidationErrorView

Formalist/FloatLabel.swift, Formalist/GroupElement.swift, Formalist/UIView+FormResponder.swift
The `nextFormResponder` of the inner `FloatLabel.textEntryView` was not being set correctly.
=> Fix responder chain not working with float labels

Formalist/UITextFieldTextEditorAdapter.swift, Formalist/UITextViewTextEditorAdapter.swift
If `TextEditorConfiguration.continuouslyUpdatesValue` is set to `false` (the default), the form value will not be updated until after the text editor finishes editing. In the case where the return key executed a custom action, the action was being executed *before* the text editor resigned its first responder status, causing the changes to not be committed. This fixes that bug by having the text editor resign first responder before executing the action.
=> Resign first responder before executing custom return key action

Formalist.xcodeproj/project.pbxproj, Formalist/BooleanElement.swift, Formalist/BooleanElementView.swift, Formalist/Convenience.swift, Formalist/EditableTextElement.swift, Formalist/FloatLabel.swift, Formalist/FloatLabelTextEditorAdapter.swift, Formalist/FormValue.swift, Formalist/SegmentElement.swift, Formalist/SegmentElementView.swift, Formalist/StaticTextElement.swift, Formalist/TextEditorAdapter.swift, Formalist/UITextFieldTextEditorAdapter.swift, Formalist/UITextViewTextEditorAdapter.swift, Formalist/UIView+ChangeObservation.swift, FormalistTests/BooleanElementTests.swift, FormalistTests/EditableTextElementTests.swift, FormalistTests/FloatLabelTests.swift, FormalistTests/SegmentElementTests.swift, FormalistTests/StaticTextElementTests.swift
Currently, bindings between `FormElement`'s and `FormValue`'s are only one-way: a user updating the value of a form element causes the `FormValue` its bound to to be updated, but updating `FormValue.value` directly doesn't cause the form element's view to be updated accordingly. This PR implements bidirectional bindings for all elements that could benefit from it (`BooleanElement`, `SegmentElement`, `EditableTextElement`, and `StaticTextElement`).
=> Two-way bindings

Example/ViewController.swift, Formalist/FloatLabel.swift
Added container view for Float Label that allows us to add 12px from the top and bottom. So clickable area become => 44px 
Added `multiLineFloatLabel` to example View Controller
=> Textfield padding

Formalist/GroupElement.swift
This is useful for verifying the state of a `GroupElement`. In a test
for example.
=> Make GroupElement#elements public

Formalist/PlaceholderTextView.swift
`PlaceholderTextView` never restore the original `textColor` after
displaying a placeholder. To understand this issue it's important to
understand that the view can be in two states: 1) Placeholder and 2)
Normal.
When the view is initialized it is in the Placeholder state. Normally
when it transitions into the placeholder state it sets
`originalTextAttributes`. However because `showPlaceholder=` is never
called during initialization `originalTextAttributes` is never set.
This is a problem because when `textColor=` is called, it correctly
detects that it's in the Placeholder state so assigns the new textcolor
to `originalTextAttributes?[NSForegroundColorAttributeName]`. Because
`originalTextAttributes` is `.None` at this point, we never keep track
of the `textColor` that we want.
The main …
=> Restore original color when not showing placeholder

Formalist/SegmentElementView.swift
Currently the spacing between the title and the segmented control is hard coded to 12pt. This PR changes it so that the default is 12pt, but customizable.
=> Allow customizing the spacing between a title and segmented control

Formalist/SegmentElementView.swift
Since `SegmentElement` is responsible for instantiating a
`SegmentElementView` there was no way for third party code to inject a
different layout. This modifies `SegmentElementView` so that it's layout
is mutable.
Using this third party code can modify the layout by providing a
`viewConfigurator` when instantiating a `SegmentElement`.
=> Allow customizing the segment layout

Formalist/Convenience.swift, Formalist/SegueElement.swift, Formalist/SegueElementView.swift
Allows user to set accessoryIcon (right icon) for  `SegueElement`
=> Added accessoryIcon to SegueElement

Example/Assets.xcassets/AppIcon.appiconset/Contents.json, Example/ViewController.swift, Formalist.xcodeproj/project.pbxproj, Formalist/EditableTextElement.swift, Formalist/FormNumberFormatter.swift, Formalist/Formattable.swift, Formalist/TextEditorConfiguration.swift, Formalist/ValidationRule.swift, FormalistTests/FormNumberFormatterTests.swift, FormalistTests/ValidationRuleTests.swift
Implemented TextFormatter to allow setting pattern formatting for specific fields. 
`TextEditorConfiguration` has a property `TextFormatter` , if user set pattern: `XXX-XXX-XXXX` and replaceCharacter: `replaceCharacter` that field would be formatted that way while tapping. 
This ideal for formatting fields like phone number, social security, EIN, credit card number.
Created `FormNumberFormatter` formatter that conform to `Formattable`, realized with @louoso that it's little tricky to support alphabetic values, for now it's gonna support just digits for formatting. 
I'm just typing number, it automatically adds `-` in between.
=> Number Formatting for Text EditableTextElement

Formalist/EditableTextElement.swift
if you initialize `let phoneValue = FormValue(“6507045868“)` and set it to text view property, it wasn’t formatted on initial value, this PR fixes this behavior
=> Format text on initial value

Example/ViewController.swift, Formalist/SegueElementView.swift
Initially could not make `UILabel` to work properly when you set `numberOfLines = 0`, setting content resistance or hugging won’t do anything. 
Stumble upon this solution: https://stackoverflow.com/a/38294467 to wrap `UILabel` into `UIView` and put it in the `stackView`.
I was surprised :) 
Result in the last two rows:
=> Support multiline title in SegueElementView 

Formalist.xcodeproj/project.pbxproj
The move to Carthage seems have resulted in the Formalist.framework embedding the StackViewController.framework. This may be the cause of some of our unrecognized selector problems when running tests, and it definitely prevents us from uploaded a build to ITC.
=> don't embed StackViewController.framework

Example/ViewController.swift, Formalist/BooleanElement.swift, Formalist/Convenience.swift, Formalist/DividerElement.swift, Formalist/EditableTextElement.swift, Formalist/FormElement.swift, Formalist/GroupElement.swift, Formalist/InfoFieldElement.swift, Formalist/SegmentElement.swift, Formalist/SegueElement.swift, Formalist/SpacerElement.swift, Formalist/StaticTextElement.swift, Formalist/ViewElement.swift, FormalistTests/EditableTextElementTests.swift, FormalistTests/GroupElementTests.swift, FormalistTests/StaticTextElementTests.swift
Make `FormElement`s more discoverable by making them static functions on the `FormElement` type. This allows Xcode to offer suggestions for `FormElement`s when someone types `FormElement.` or `FormElement.group([.`
To accomplish this `FormElement` had to be changed from a `protocol` to a class intended for subclassing. This is because in Swift static members on a protocol can only be accessed through an implementation of the protocol. This would defeat the purpose because then users would have to type `BooleanElement.` and Xcode would suggest the `boolean` static function.
=> Make the different FormElements more discoverable

Formalist/Convenience.swift
The project using this framework couldn't see the new extension methods; this makes sure they're available.
=> Make extension methods public

Formalist/AccessoryViewToolbar.swift, Formalist/TextEditorConfiguration.swift, Formalist/UITextFieldTextEditorAdapter.swift
Some actions associated with the `done` button may be more clearly represented with different text; this allows users to specify a more descriptive title when needed.
=> Allow customization of 'done' button title

CHANGELOG.md, Example/FormViewController.swift, Example/ViewController.swift, Formalist.xcodeproj/project.pbxproj, Formalist/FormViewController.swift, FormalistUITests/FormalistUITests.swift
Allow `FormViewController` to be subclassed so that forms that take up the entire available space of a view controller's view don't have to do the `addChildViewController` dance. Subclasses can set up their own forms by calling the superclass' `init(elements:)` or `init(rootElement)` designated initializers.
This also updates the example project with an example of a subclassed `FormViewController`.
=> Allow subclassing of FormViewController

CHANGELOG.md, Example/ViewController.swift, Formalist.xcodeproj/project.pbxproj, Formalist/TextEditor.swift, Formalist/UITextFieldTextEditorAdapter.swift, Formalist/UITextViewTextEditorAdapter.swift
Change UITextViewTextEditorAdapter to honor `TextEditorConfiguration.showAccessoryViewToolbar`. If it's set to `true` the adapter will now show the toolbar when the text view becomes first responder.
=> Support accessory toolbar for multiline float labels

Formalist.podspec, Formalist/GroupElement.swift
This will allow the "Next" button to jump across groups.
=> Linking all responder views within a GroupElement (including nested ones)

Formalist.podspec, Formalist/FloatLabel.swift, Formalist/GroupElement.swift, Formalist/TextEditor.swift, Formalist/UITextFieldTextEditorAdapter.swift, Formalist/UITextViewTextEditorAdapter.swift, Formalist/UIView+FormResponder.swift
I reverted back to the previous `render()` implementation and then added a private array of responder views that can be grabbed from nested `GroupElement`s.
Here is a link to compare the changes between the last working commit and this new commit to see the actual changes: https://github.com/seedco/Formalist/compare/0.6.0...dm-fix-group-insets?expand=1
=> Reverted changes for PR #75 and reimplements it w/out breaking the group insets.
